

var feedback_Array = [
    ["Du har muligvis eksamensangst", "Ifølge testen tyder det på, at du har eksamensangst og har brug for hjælp. <br/>Jo før du går i gang med at forberede dig på eksamen, desto bedre.<br/><br/>Du har især brug for at arbejde systematisk med ØVELSER, der hjælper dig med at genkende tanker og følelser, og lærer dig at tænke konstruktivt om eksamen.<br/><br/><a href='http://publ.e-undervisning.net/Kursist/Redskaber/47/Sider/oevelser.aspx' target=‘_blank’ class='btn btn-main btn_feed' role='button'>Skemaøvelser</a> <br/><br/>Du bør også træne visualisering, vejrtrækning og afspænding. Hør øvelserne her: <br/><br/><a href='http://publ.e-undervisning.net/Kursist/Redskaber/47/Sider/lytteoevelser.aspx' target=‘_blank’ class='btn btn-main btn_feed' role='button'>Lytteøvelser</a><br/><br/>Se også disse “Stop panik” øvelser, som du kan bruge i eksamenssituationen<br/><br/><a href='http://publ.e-undervisning.net/Kursist/Redskaber/47/Sider/stoppanik.aspx' target=‘_blank’ class='btn btn-main btn_feed' role='button'>Stop panikken</a>"],
    ["Du har måske mild eksamensangst", "Du kender til følelsen af eksamensangst, men oplever at du kan tackle eksamen. Du ønsker at blive bedre til at gå til eksamen, da angsten stadig er for dominerende. Du har især brug for at træne Stop-panik øvelserne:<br/> <a href=‘http://publ.e-undervisning.net/Kursist/Redskaber/47/Sider/stoppanik.aspx' target=‘_blank’ class='btn btn-main btn_feed' role='button'>Stop panikken</a> <br/><br/>Du bør også træne vejrtrækning og visualiseringsøvelserne:<br/><br/><a href='http://publ.e-undervisning.net/Kursist/Redskaber/47/Sider/lytteoevelser.aspx' target=‘_blank’ class='btn btn-main btn_feed' role='button'>Lytteøvelser</a><br/><br/> Læs evt. også de to interviews her:<br/><br/><a href='http://publ.e-undervisning.net/Kursist/Redskaber/47/Sider/teori.aspx' target=‘_blank’ class='btn btn-main btn_feed' role='button'>Interviews</a>"],
    ["Du er moderat nervøs.", " Du kan håndtere eksamen og har styr på dig selv, dine tanker og reaktioner. Nervøsiteten kan være lidt generende ind imellem. <br/><br/>At træne vejrtrækning, visualisering og afspænding vil være enkle redskaber for at forbedre din eksamen og få kontrol over dig selv og din anspændthed.<br/><br/><a href='http://publ.e-undervisning.net/Kursist/Redskaber/47/Sider/lytteoevelser.aspx' target=‘_blank’ class='btn btn-main btn_feed' role='button'>Lytteøvelser</a>"],
    ["Du er cool.", "Du er ikke specielt påvirket og lader dig ikke slå ud, når du går til eksamen. Du har kontrol over situationen, er tilfreds med dine præstationer og klarer dig generelt som du forventer.<br/><br/> Du kan eventuelt bruge nogle af disse afslapningsøvelser: <br/><br/>a href='http://publ.e-undervisning.net/Kursist/Redskaber/47/Sider/lytteoevelser.aspx' target=‘_blank’ class='btn btn-main btn_feed' role='button'>Lytteøvelser</a>"]
];

alert(feedback_Array);
